### ISSUE TITLE
Ukrainian (uk) language

### ISSUE THREAD

**Issue by boomsya** [hodgef/simple-keyboard-layouts#128]
please take this. Edited by myself.

```
const uk = {
  default: [
    "\u0027 1 2 3 4 5 6 7 8 9 0 - = {bksp}",
    "{tab} \u0439 \u0446 \u0443 \u043a \u0435 \u043d \u0433 \u0448 \u0449 \u0437 \u0445 \u0457 \\",
    "{lock} \u0444 \u0456 \u0432 \u0430 \u043f \u0440 \u043e \u043b \u0434 \u0436 \u0454 {enter}",
    "{shift} \\ \u044f \u0447 \u0441 \u043c \u0438 \u0442 \u044c \u0431 \u044e / {shift}",
    ".com @ {space}"
  ],
  shift: [
    '\u20B4 ! " \u2116 ; % : ? * ( ) _ + {bksp}',
    "{tab} \u0419 \u0426 \u0423 \u041a \u0415 \u041d \u0413 \u0428 \u0429 \u0417 \u0425 \u0407 /",
    "{lock} \u0424 \u0406 \u0412 \u0410 \u041f \u0420 \u041e \u041b \u0414 \u0416 \u0404 {enter}",
    "{shift} / \u042f \u0427 \u0421 \u041c \u0418 \u0422 \u042c \u0411 \u042e / {shift}",
    ".com @ {space}"
  ]
};

export default uk;
```

**Comment by hodgef** [comment]
Thank you @boomsya !

Do you mind [adding your layout to a pull request](https://github.com/hodgef/simple-keyboard-layouts/wiki/Adding-a-Layout#how-to-add-a-new-layout)? It's so you can be credited as a [contributor](https://github.com/hodgef/simple-keyboard-layouts/graphs/contributors) :)

Regards,
Francisco Hodge

**Comment by boomsya** [comment]
Yes. If you can - add please to new release. I dont wand to be contributor. I have use your component virtual-keyboard with 3 languages. Ukrainian land was missed in list. So i was modified layout to my native lang

**Comment by hodgef** [comment]
Sounds good, thanks again, I'll merge this in shortly !
