### ISSUE TITLE
Start project error

### ISSUE THREAD

**Issue by gd-ldj** [hodgef/simple-keyboard-layouts#40]
When I npm run start, it gives an error

![image](https://user-images.githubusercontent.com/34954129/58089689-048d8480-7bf8-11e9-97df-c27de7773fe8.png)

**Comment by hodgef** [comment]
Hello @gd-ldj, thanks for the report! I haven't been able to reproduce this issue however:

![image](https://user-images.githubusercontent.com/25509135/58096131-658a6d80-7ba2-11e9-990d-3326ee5032fd.png)

Also in Travis CI the dev server seems to be starting after a fresh install:
https://travis-ci.org/hodgef/simple-keyboard-layouts/builds/535269677#L517

Could you clone the project again and run `npm install` ? At this point I'm not sure if it's an issue of this repo, a bad install, or a need to update node.

Regards,
Francisco Hodge

**Comment by gd-ldj** [comment]
Thanks , I regitated `git clone` and then operated it once, it is ok
